### ISSUE TITLE
sample_raycast.cの整理

### ISSUE THREAD

**Issue by kamitsui** [1RO8s/cub3D#22]
残す？ -> `practice_code` ディレクトリに入れる？？
現在のコードに反映するものもある？
例
・TILE_SIZE ... ?
・魚眼レンズの補正 ... ?

**Comment by 1RO8s** [comment]
> 残す？ -> practice_code ディレクトリに入れる？？

一応残しておきたいので、practice_codeディレクトリに入れたいです

>・TILE_SIZE ... ?

１マス分長さです。１で計算してると思うので反映不要です。
>・魚眼レンズの補正 ... ?

対応してあったと思うので反映不要です。
